### ISSUE TITLE
Shell completion (and other) text not visible (very faint)

### ISSUE THREAD

**Issue by hajosattila** [dracula/foot#3]
Arch Linux | 5.19.7-AMD | sway version: 1.7 | foot version: 1.13.1 | Dracula theme
foot.ini: https://pastebin.com/s2tRCWkb

![scrn-2022-09-11-10-52-23](https://user-images.githubusercontent.com/1567493/189521275-d71399e2-f740-45c0-bf01-768136c545b2.png)

![scrn-2022-09-11-11-46-17](https://user-images.githubusercontent.com/1567493/189521286-8cf202e6-4d28-4a7b-8218-2eef7b425b89.png)

Sorry for my bad English!

**Comment by syrofoam** [comment]
Issue was patched with the merge request and the colors where updated.
If you update or download latest you should be good.
